#!/usr/bin/env python3
"""Generate a READ-ONLY SQL probe answering, per migration file: is it recorded in
supabase_migrations.schema_migrations, and do the objects it creates exist?

    python3 scripts/deploy/migration-probes.py > /tmp/migration-status.sql
    psql "$DB_URL" -At -f /tmp/migration-status.sql      # or scripts/security/verify-rls.sh-style docker psql

"Recorded but objects missing" and "objects present but not recorded" (applied out
of band) are the two states a reconciliation has to resolve. Production's history
was written through the MCP channel, which assigns its OWN version and keeps the
NAME (docs/SUPABASE_TARGETING.md), so a file is matched both ways. The probes are
derived from the SQL itself: CREATE TABLE / FUNCTION / INDEX / POLICY / VIEW and
ADD COLUMN statements. A migration that only changes data or grants has no probe
and reports objects: null."""
import os, re, sys, json

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FOLDERS = [("migrations", "supabase/migrations"), ("held", "supabase/migrations-held")]

RE = {
    "table": re.compile(r"create\s+table\s+(?:if\s+not\s+exists\s+)?(?:public\.)?\"?([a-z_][a-z0-9_]*)\"?", re.I),
    "function": re.compile(r"create\s+(?:or\s+replace\s+)?function\s+(?:public\.)?\"?([a-z_][a-z0-9_]*)\"?\s*\(", re.I),
    "index": re.compile(r"create\s+(?:unique\s+)?index\s+(?:concurrently\s+)?(?:if\s+not\s+exists\s+)?\"?([a-z_][a-z0-9_]*)\"?\s+on", re.I),
    "view": re.compile(r"create\s+(?:or\s+replace\s+)?view\s+(?:public\.)?\"?([a-z_][a-z0-9_]*)\"?", re.I),
    "policy": re.compile(r"create\s+policy\s+\"([^\"]+)\"\s+on\s+((?:public|storage)\.)?\"?([a-z_][a-z0-9_]*)", re.I),
}
ADD_COL = re.compile(r"alter\s+table\s+(?:if\s+exists\s+)?(?:only\s+)?(?:public\.)?\"?([a-z_][a-z0-9_]*)\"?\s+((?:[^;])*?)(?:;)", re.I | re.S)
COL = re.compile(r"add\s+column\s+(?:if\s+not\s+exists\s+)?\"?([a-z_][a-z0-9_]*)\"?", re.I)

def strip_comments(sql: str) -> str:
    sql = re.sub(r"--[^\n]*", "", sql)
    return re.sub(r"/\*.*?\*/", "", sql, flags=re.S)

def probes(sql: str):
    s = strip_comments(sql)
    out = []
    for kind in ("table", "function", "index", "view"):
        for name in sorted(set(RE[kind].findall(s))):
            out.append((kind, name, None))
    for pol, schema, tbl in sorted(set(RE["policy"].findall(s))):
        out.append(("policy", pol, (schema.rstrip(".") or "public") + "." + tbl))
    for tbl, body in ADD_COL.findall(s):
        for col in COL.findall(body):
            out.append(("column", col, tbl))
    return out

def sql_for(kind, name, extra):
    q = lambda v: "'" + v.replace("'", "''") + "'"
    if kind == "table":
        return f"exists(select 1 from pg_tables where schemaname='public' and tablename={q(name)})"
    if kind == "function":
        return f"exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname={q(name)})"
    if kind == "index":
        return f"exists(select 1 from pg_indexes where indexname={q(name)})"
    if kind == "view":
        return f"exists(select 1 from pg_views where schemaname='public' and viewname={q(name)})"
    if kind == "policy":
        schema, table = extra.split(".", 1)
        return f"exists(select 1 from pg_policies where schemaname={q(schema)} and tablename={q(table)} and policyname={q(name)})"
    if kind == "column":
        return f"exists(select 1 from information_schema.columns where table_schema='public' and table_name={q(extra)} and column_name={q(name)})"
    raise ValueError(kind)

rows = []
for folder, rel in FOLDERS:
    d = os.path.join(REPO, rel)
    for f in sorted(os.listdir(d)):
        if not f.endswith(".sql"):
            continue
        version = f.split("_", 1)[0]
        ps = probes(open(os.path.join(d, f)).read())
        # The baseline creates everything; probing 1,000 objects says nothing a
        # handful does not, so it is sampled.
        if "baseline" in f:
            ps = [p for p in ps if p[0] == "table"][:12]
        checks = [f"json_build_object('kind',{json.dumps(k)!r}::text,'name',{json.dumps(n)!r}::text,'present',{sql_for(k, n, e)})".replace('\'"', "'").replace('"\'', "'") for k, n, e in ps]
        arr = "json_build_array(" + ",".join(checks) + ")" if checks else "null"
        rows.append(f"select {json.dumps(folder)!r}::text as folder, '{version}' as version, '{f}' as file, "
                    f"exists(select 1 from supabase_migrations.schema_migrations m where m.version = '{version}') as recorded, "
                    f"exists(select 1 from supabase_migrations.schema_migrations m where m.name = '{f[len(version) + 1:-4]}') as recorded_by_name, "
                    f"{arr} as objects")

print("-- GENERATED by scripts/deploy/migration-probes.py — READ ONLY.")
print("begin transaction read only;")
print("select json_agg(t) from (")
print("\nunion all\n".replace("\n", "\n").join(rows).replace("\"", "") if False else "\nunion all\n".join(r.replace('"', "") for r in rows))
print(") t;")
print("rollback;")
