// WHY THIS FILE EXISTS.
//
// `supabase/migrations/` now holds ONE file, and it is the only thing that can
// rebuild this database. The 99 files that preceded it are archived because
// they could not: `scheduled_emails` was ALTERed seven months before it was
// CREATEd, seven tables had no CREATE statement anywhere, and the previous
// baseline captured 83 tables while explicitly capturing no policies, no
// foreign keys, no triggers and no enums.
//
// The schema-contract tests elsewhere read the ARCHIVED migrations — they
// assert that a historical change was written correctly, which is still worth
// knowing but is no longer what builds anything. Nothing was checking the file
// that does. These tests are that check.
//
// They deliberately count rather than parse. A baseline is regenerated by
// `pg_dump`, so its exact text will change; what must not change is that it
// still carries every class of object, and above all the ROW-LEVEL SECURITY.
// A baseline that silently lost its policies would restore 109 tables readable
// by any authenticated user, and every other test here would still pass.
import { assert, assertEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";

const BASELINE = await Deno.readTextFile(
  new URL("../../supabase/migrations/20260816120000_baseline_schema.sql", import.meta.url),
);

const count = (re: RegExp) => (BASELINE.match(re) ?? []).length;

Deno.test("the baseline is the only migration", async () => {
  // A second file here is not automatically wrong — new migrations belong after
  // the baseline. What would be wrong is the ARCHIVE creeping back, so this
  // asserts the baseline is present and that the unreplayable chain has not
  // returned alongside it.
  const dir = new URL("../../supabase/migrations/", import.meta.url);
  const names: string[] = [];
  for await (const e of Deno.readDir(dir)) if (e.name.endsWith(".sql")) names.push(e.name);
  assert(names.includes("20260816120000_baseline_schema.sql"), "the baseline must be present");
  assert(
    !names.includes("20260526000000_baseline_from_prod.sql"),
    "the old incomplete baseline must stay archived — it carries no RLS policies",
  );
});

Deno.test("it creates every class of object, not just tables", () => {
  // The failure mode of the PREVIOUS baseline, encoded. It had tables and
  // nothing else, and that was only discoverable by reading its header.
  assertEquals(count(/^CREATE TABLE /gm), 109, "tables");
  assertEquals(count(/^CREATE POLICY /gm), 269, "RLS policies");
  assertEquals(count(/^CREATE FUNCTION /gm), 21, "functions");
  assertEquals(count(/^CREATE TRIGGER /gm), 39, "triggers");
  assertEquals(count(/^CREATE TYPE /gm), 18, "enums");
  assert(count(/^CREATE (UNIQUE )?INDEX /gm) >= 180, "indexes");
  assert(count(/FOREIGN KEY/g) >= 150, "foreign keys");
});

Deno.test("every table has row-level security enabled", () => {
  // THE ONE THAT MATTERS MOST. 109 tables, 109 ENABLE ROW LEVEL SECURITY. A
  // baseline that restored the tables and dropped this would look completely
  // healthy — right table count, right column types, application boots — while
  // exposing every row to any authenticated user.
  assertEquals(
    count(/ENABLE ROW LEVEL SECURITY/g), 109,
    "one per table; a shortfall here is a data leak, not a formatting change",
  );
});

Deno.test("it can be applied to a fresh Supabase project", () => {
  // A brand-new project already has `public`. An unguarded CREATE SCHEMA aborts
  // the whole migration on the first statement — which is exactly the class of
  // bug that made the previous chain unreplayable.
  assert(
    /CREATE SCHEMA IF NOT EXISTS public;/.test(BASELINE),
    "CREATE SCHEMA must be guarded, or the first push into a fresh project fails",
  );
  assert(!/^CREATE SCHEMA public;/m.test(BASELINE));
});

Deno.test("it names no retired project", () => {
  // The dump was taken from the old database. Its DDL must not carry that
  // project's identity forward into the file that defines every new one.
  for (const retired of ["zbwsbnqqpkvdhqwavjke", "wqnigjhcwjxtmordrwno", "luvostyizefajbltukkc"]) {
    assertEquals(BASELINE.includes(retired), false, `${retired} must not appear in the baseline`);
  }
});

Deno.test("it does not schedule the cron job that filled the disk", () => {
  // The archived 20251206101250 scheduled an every-minute job posting to a
  // hardcoded project URL with a hardcoded anon JWT. It wrote 455 MB into
  // cron.job_run_details, filled a 500 MB quota and took the app down. A
  // regenerated baseline must never quietly bring it back.
  assert(!/cron\.schedule\s*\(/i.test(BASELINE), "the baseline must schedule nothing");
  assert(!/net\.http_post/i.test(BASELINE), "and must post to nothing");
});

Deno.test("the archive is preserved, not deleted", async () => {
  // The history is how the schema got here and is still read by the
  // schema-contract tests. Squashing must not destroy it.
  const dir = new URL("../../supabase/migrations-archive/", import.meta.url);
  let n = 0;
  for await (const e of Deno.readDir(dir)) if (e.name.endsWith(".sql")) n++;
  assertEquals(n, 99, "all 99 archived migrations must remain");
});
