// A SHOWCASE PAGE IS NOT A COMPANY.
//
// Discovery for task 783fa163 returned 30 rows. FIVE of them were LinkedIn
// showcase pages, and every one entered the candidate pool:
//
//     LinkedIn Guide to Creating      SHOWCASE   employeeCount: absent
//     Zip, a puzzle by LinkedIn       SHOWCASE   employeeCount: absent
//     LinkedIn Guide to Networking    SHOWCASE   employeeCount: absent
//     LinkedIn News                   SHOWCASE   employeeCount: 8
//     Google for Developers           SHOWCASE   employeeCount: 1700
//
// A showcase page is a marketing surface belonging to a parent company. It has
// no headcount to gate on, nobody to contact, and it DUPLICATES a company
// already in the pool — LinkedIn News is LinkedIn, Google for Developers is
// Google.
//
// THEY WERE NOT FREE. `normalizeCompanyLinkedInUrl` requires a `/company/`
// path, so every showcase row normalised to a null `linkedin_company_url`,
// which sent identity resolution to its NAME fallback — and it spent a paid
// search on the literal string "LinkedIn Guide to Creating". Two rows ended
// that run as `identity_unresolved` for a question with no answer.
//
// ONE WAS WORSE THAN WASTED. "LinkedIn News" reports 8 employees, making it the
// ONLY row in that entire pool inside the workspace's 1-150 headcount policy —
// the single company a size-filtered search would have kept. An editorial page
// was the run's best candidate.
//
// Every row below is copied from Apify dataset ddhW0U9a7HsLtNEzi.
//
// Pure. No network, no provider, no model call.

import { assert, assertEquals } from "https://deno.land/std@0.224.0/assert/mod.ts";
import {
  nonCompanyPageReason,
  normalizeLinkedInCompanyCandidate,
} from "../../../supabase/functions/_shared/hiringActorNormalizers.ts";

/** Verbatim rows from the live discovery dataset. */
const SHOWCASES = [
  { name: "LinkedIn Guide to Creating", id: "74310544", autoGenerated: false,
    pageType: "SHOWCASE", universalName: "linkedin-guide-to-creating",
    linkedinUrl: "https://www.linkedin.com/showcase/linkedin-guide-to-creating/" },
  { name: "Zip, a puzzle by LinkedIn", id: "106668294", autoGenerated: false,
    pageType: "SHOWCASE", universalName: "zip-game",
    linkedinUrl: "https://www.linkedin.com/showcase/zip-game/" },
  { name: "LinkedIn News", id: "11280505", autoGenerated: false,
    pageType: "SHOWCASE", universalName: "linkedin-news", employeeCount: 8,
    linkedinUrl: "https://www.linkedin.com/showcase/linkedin-news/" },
  { name: "LinkedIn Guide to Networking", id: "14041259", autoGenerated: false,
    pageType: "SHOWCASE", universalName: "linkedin-member-guide",
    linkedinUrl: "https://www.linkedin.com/showcase/linkedin-member-guide/" },
  { name: "Google for Developers", id: "25013385", autoGenerated: false,
    pageType: "SHOWCASE", universalName: "googledevelopers", employeeCount: 1700,
    linkedinUrl: "https://www.linkedin.com/showcase/googledevelopers/" },
];

const REAL_COMPANIES = [
  { name: "Adobe", id: "1480", autoGenerated: false, pageType: "COMPANY",
    employeeCount: 42902, companyType: "Public Company",
    linkedinUrl: "https://www.linkedin.com/company/adobe/" },
  { name: "GitHub", id: "1418841", autoGenerated: false, pageType: "COMPANY",
    employeeCount: 6810, companyType: "Privately Held",
    linkedinUrl: "https://www.linkedin.com/company/github/" },
  { name: "Amazon", id: "1586", autoGenerated: false, pageType: "COMPANY",
    employeeCount: 769019, companyType: "Public Company",
    linkedinUrl: "https://www.linkedin.com/company/amazon/" },
];

Deno.test("all five live showcase rows are refused", () => {
  for (const r of SHOWCASES) {
    assertEquals(nonCompanyPageReason(r), "showcase_page", r.name);
  }
});

Deno.test("every real company in the same dataset is kept", () => {
  for (const r of REAL_COMPANIES) {
    assertEquals(nonCompanyPageReason(r), null, r.name);
  }
});

Deno.test("the pool loses exactly 5 of the 30 rows", () => {
  const pool = [...SHOWCASES, ...REAL_COMPANIES];
  const kept = pool.filter((r) => nonCompanyPageReason(r) === null);
  assertEquals(pool.length - kept.length, SHOWCASES.length);
  assertEquals(kept.map((r) => r.name), ["Adobe", "GitHub", "Amazon"]);
});

Deno.test("the 8-employee row that would have passed a size filter is gone", () => {
  // THE ONE THAT MATTERS. With the Brain's 1-150 policy now reaching discovery,
  // "LinkedIn News" is the single row of that pool a filtered search returns —
  // so dropping it is the difference between a clean empty result and a
  // confident wrong one.
  const news = SHOWCASES.find((r) => r.name === "LinkedIn News")!;
  assertEquals(news.employeeCount, 8, "in range for a 1-150 policy");
  assertEquals(nonCompanyPageReason(news), "showcase_page");
});

// ── ABSENCE IS NEVER A DROP ───────────────────────────────────────────────

Deno.test("a short-mode row with no pageType is kept", () => {
  // Identity resolution runs the SAME Actor in `short` mode, whose rows carry
  // only followers, id, industry, linkedinUrl, logo, name, summary,
  // universalName, location — no pageType at all (run xpbBeCelqBx6zU7RF). An
  // allow-list on `pageType === "COMPANY"` would drop every identity row ever
  // resolved.
  assertEquals(nonCompanyPageReason({
    id: "1480", name: "Adobe", industry: "Software Development",
    linkedinUrl: "https://www.linkedin.com/company/adobe/",
  }), null);
});

Deno.test("the URL path still catches a showcase in short mode", () => {
  // The signal that survives the mode change: `/showcase/` is in the URL
  // whether or not `pageType` was returned.
  assertEquals(nonCompanyPageReason({
    id: "11280505", name: "LinkedIn News",
    linkedinUrl: "https://www.linkedin.com/showcase/linkedin-news/",
  }), "showcase_page");
});

Deno.test("an empty row is not a company and not a crash", () => {
  assertEquals(nonCompanyPageReason({}), null, "nothing stated, nothing inferred");
});

Deno.test("autoGenerated and school pages are caught, and named separately", () => {
  // `autoGenerated` was FALSE on all 30 rows of that run including the five
  // showcases — it is a real field and a different case, not the one that
  // caught these. Kept because it is cheap and correct.
  assertEquals(
    nonCompanyPageReason({ autoGenerated: true, linkedinUrl: "https://www.linkedin.com/company/x/" }),
    "auto_generated_page");
  assertEquals(
    nonCompanyPageReason({ linkedinUrl: "https://www.linkedin.com/school/mit/" }),
    "showcase_page");
  assertEquals(
    nonCompanyPageReason({ pageType: "GROUP", linkedinUrl: "https://www.linkedin.com/company/x/" }),
    "non_company_page_type:GROUP",
    "an unknown page type is reported by name rather than silently allowed");
});

// ── WHY THEY COST MONEY, PINNED ───────────────────────────────────────────

Deno.test("a showcase row normalises to a null company URL — the paid name search", () => {
  const n = normalizeLinkedInCompanyCandidate(SHOWCASES[0]);
  assertEquals(
    n.linkedin_company_url, null,
    "no /company/ path, so identity resolution falls back to searching the NAME",
  );
  assertEquals(n.company_name, "LinkedIn Guide to Creating",
    "which is the literal string run 783fa163 paid to search for");
});

// ── THE CALL SITES ────────────────────────────────────────────────────────

Deno.test("the capability engine drops them before any paid identity call", () => {
  const ENGINE = Deno.readTextFileSync(
    new URL("../../../supabase/functions/_shared/leadCapabilityEngine.ts", import.meta.url),
  );
  const i = ENGINE.indexOf("const droppedPages = new Map<string, number>()");
  assert(i > 0, "the pool boundary must filter");
  const block = ENGINE.slice(i, i + 2400);
  assert(block.includes("const notACompany = nonCompanyPageReason(r)"));
  assert(
    block.indexOf("continue;") < block.indexOf("addCompany(companies"),
    "the drop must happen before the row joins the pool",
  );
  assert(
    block.includes('outcome: "rows_dropped"'),
    "a pool that shrank must say why, or the next audit re-derives it from Apify",
  );
});

Deno.test("the legacy company-first executor drops them too", () => {
  // Two pool builders, one rule. A route that admits a candidate the engine
  // refuses is how a fix half-lands.
  const EXEC = Deno.readTextFileSync(
    new URL("../../../supabase/functions/_shared/companyFirstRouteExecutor.ts", import.meta.url),
  );
  assert(EXEC.includes("nonCompanyPageReason(r) === null"));
});
