// Workflow Capability Registry — single source of truth for what Agentory can do.
// Used by Pilot for routing/Q&A, the empty-state UI, and capability-aware
// clarifications. Server-side mirror lives in
// supabase/functions/_shared/workflows/capabilities.ts.

export type AgentId = 'pilot' | 'scout' | 'aria' | 'penn' | 'hawk' | 'scribe';

export type SafetyLevel = 'safe' | 'draft_only' | 'approval_required' | 'blocked';

export type WorkflowCapability = {
  id: string;
  name: string;
  description: string;
  example_prompts: string[];
  required_context: string[];
  optional_context: string[];
  agents: AgentId[];
  tools: string[];
  output_kind: 'workbench' | 'chat' | 'draft' | 'report' | 'export';
  requires_confirmation?: boolean;
  safety_level: SafetyLevel;
  enabled: boolean;
  fallback?: string;
};

export const WORKFLOW_CAPABILITIES: WorkflowCapability[] = [
  // ──────────────── GTM / Lead ────────────────
  {
    id: 'find_leads',
    name: 'Find leads',
    description: 'Source new accounts or contacts matching your ICP.',
    example_prompts: ['Find me leads', 'Find 20 SaaS founders in NYC'],
    required_context: [],
    optional_context: ['icp', 'geography', 'role', 'count'],
    agents: ['pilot', 'scout', 'aria'],
    tools: ['apify_jobs', 'apify_people', 'firecrawl'],
    output_kind: 'workbench',
    safety_level: 'safe',
    enabled: true,
    fallback: 'hiring_signal_search',
  },
  {
    id: 'hiring_signal_search',
    name: 'Hiring-signal company search',
    description: 'Find companies hiring specific roles right now (jobs actor).',
    example_prompts: ['Find 5 companies hiring GTM roles in B2B SaaS in USA'],
    required_context: ['role_keywords'],
    optional_context: ['geography', 'industry', 'count'],
    agents: ['pilot', 'scout', 'aria'],
    tools: ['apify_jobs'],
    output_kind: 'workbench',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'icp_company_search',
    name: 'ICP company search',
    description: 'Find companies matching ICP criteria from Company Brain.',
    example_prompts: ['Find accounts that match our ICP'],
    required_context: ['icp'],
    optional_context: ['geography', 'industry', 'size', 'count'],
    agents: ['pilot', 'scout', 'aria'],
    tools: ['firecrawl', 'apify_jobs'],
    output_kind: 'workbench',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'founder_profile_search',
    name: 'Founder / profile search',
    description: 'Find people profiles (founders, decision-makers) by criteria.',
    example_prompts: ['Find 5 healthcare AI founders in London'],
    required_context: ['persona'],
    optional_context: ['geography', 'industry', 'count'],
    agents: ['pilot', 'scout'],
    tools: ['apify_people'],
    output_kind: 'workbench',
    safety_level: 'safe',
    enabled: true,
    fallback: 'linkedin_intent_posts',
  },
  {
    id: 'linkedin_intent_posts',
    name: 'LinkedIn intent posts',
    description: 'Find LinkedIn posts signalling buying intent on a topic.',
    example_prompts: ['Find people talking about Clay alternatives'],
    required_context: ['topic'],
    optional_context: ['geography', 'count'],
    agents: ['pilot', 'hawk'],
    tools: ['apify_posts'],
    output_kind: 'workbench',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'linkedin_comments_engagement',
    name: 'LinkedIn comments engagement',
    description: 'Surface engaged commenters on a post or set of posts.',
    example_prompts: ['Who commented on this LinkedIn post?'],
    required_context: ['post_url'],
    optional_context: [],
    agents: ['pilot', 'hawk'],
    tools: ['apify_comments'],
    output_kind: 'workbench',
    safety_level: 'safe',
    enabled: true,
    fallback: 'linkedin_intent_posts',
  },
  {
    id: 'competitor_engagement',
    name: 'Competitor engagement',
    description: 'Find people engaging with competitors on LinkedIn.',
    example_prompts: ['Find people engaging with Clay'],
    required_context: ['competitor'],
    optional_context: ['count'],
    agents: ['pilot', 'hawk'],
    tools: ['apify_posts', 'apify_comments'],
    output_kind: 'workbench',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'find_decision_makers',
    name: 'Find decision-makers',
    description: 'Add contacts to existing accounts in the workbench.',
    example_prompts: ['Find decision-makers at these companies'],
    required_context: ['accounts'],
    optional_context: ['persona'],
    agents: ['pilot', 'scout'],
    tools: ['apify_people', 'firecrawl'],
    output_kind: 'workbench',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'enrich_companies',
    name: 'Enrich companies',
    description: 'Enrich accounts with website, tech, headcount, news.',
    example_prompts: ['Enrich these accounts'],
    required_context: ['accounts'],
    optional_context: [],
    agents: ['pilot', 'hawk'],
    tools: ['firecrawl'],
    output_kind: 'workbench',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'rank_leads',
    name: 'Rank leads',
    description: 'Score and rank current leads by fit.',
    example_prompts: ['Rank these leads', 'Who are the best 10?'],
    required_context: ['leads'],
    optional_context: ['icp'],
    agents: ['pilot', 'aria'],
    tools: ['gemini'],
    output_kind: 'workbench',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'draft_outreach',
    name: 'Draft outreach',
    description: 'Draft personalized outbound messages (DRAFT-ONLY).',
    example_prompts: ['Draft outreach for these leads'],
    required_context: ['contacts'],
    optional_context: ['offer', 'angle', 'tone'],
    agents: ['pilot', 'penn'],
    tools: ['gemini', 'claude'],
    output_kind: 'draft',
    requires_confirmation: true,
    safety_level: 'draft_only',
    enabled: true,
  },
  {
    id: 'export_leads',
    name: 'Export leads',
    description: 'Export current workbench leads to CSV.',
    example_prompts: ['Export to CSV'],
    required_context: ['leads'],
    optional_context: [],
    agents: ['pilot'],
    tools: ['csv_export'],
    output_kind: 'export',
    safety_level: 'safe',
    enabled: true,
  },

  // ──────────────── Market / competitor ────────────────
  {
    id: 'competitor_tracking',
    name: 'Competitor tracking',
    description: 'Continuously monitor competitors for changes/signals.',
    example_prompts: ['Track our competitors'],
    required_context: ['competitors'],
    optional_context: [],
    agents: ['pilot', 'hawk'],
    tools: ['firecrawl'],
    output_kind: 'workbench',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'competitor_analysis',
    name: 'Competitor analysis',
    description: 'Deep analysis of competitors: positioning, pricing, GTM.',
    example_prompts: ['Analyze our competitors'],
    required_context: [],
    optional_context: ['competitors'],
    agents: ['pilot', 'hawk'],
    tools: ['firecrawl', 'gemini'],
    output_kind: 'report',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'pricing_page_analysis',
    name: 'Pricing-page analysis',
    description: 'Extract and compare pricing across competitors.',
    example_prompts: ['Compare competitor pricing'],
    required_context: ['competitors'],
    optional_context: [],
    agents: ['pilot', 'hawk'],
    tools: ['firecrawl'],
    output_kind: 'report',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'website_audit',
    name: 'Website audit',
    description: 'Audit a website for messaging, conversion, and SEO basics.',
    example_prompts: ['Audit acme.com'],
    required_context: ['domain'],
    optional_context: [],
    agents: ['pilot', 'hawk'],
    tools: ['firecrawl', 'gemini'],
    output_kind: 'report',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'landing_page_audit',
    name: 'Landing-page audit',
    description: 'Critique a landing page (hero, proof, CTA, friction).',
    example_prompts: ['Audit this landing page'],
    required_context: ['url'],
    optional_context: ['audience'],
    agents: ['pilot', 'scribe'],
    tools: ['firecrawl', 'gemini'],
    output_kind: 'report',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'positioning_analysis',
    name: 'Positioning analysis',
    description: 'Map positioning vs competitors; surface white-space.',
    example_prompts: ['Where can we win?'],
    required_context: [],
    optional_context: ['competitors', 'icp'],
    agents: ['pilot', 'hawk', 'scribe'],
    tools: ['gemini'],
    output_kind: 'report',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'market_research',
    name: 'Market research',
    description: 'Research a market, segment, or trend.',
    example_prompts: ['Research the AI SDR market'],
    required_context: ['topic'],
    optional_context: [],
    agents: ['pilot', 'hawk'],
    tools: ['firecrawl', 'gemini'],
    output_kind: 'report',
    safety_level: 'safe',
    enabled: true,
  },

  // ──────────────── Content ────────────────
  {
    id: 'linkedin_post_draft',
    name: 'LinkedIn post draft',
    description: 'Draft a LinkedIn post (DRAFT-ONLY).',
    example_prompts: ['Write a LinkedIn post about our launch'],
    required_context: ['topic'],
    optional_context: ['voice', 'cta'],
    agents: ['pilot', 'scribe'],
    tools: ['gemini'],
    output_kind: 'draft',
    safety_level: 'draft_only',
    enabled: true,
  },
  {
    id: 'content_calendar',
    name: 'Content calendar',
    description: 'Plan a 1–4 week content calendar.',
    example_prompts: ['Plan next month of content'],
    required_context: [],
    optional_context: ['themes', 'cadence'],
    agents: ['pilot', 'scribe'],
    tools: ['gemini'],
    output_kind: 'workbench',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'founder_post_from_signals',
    name: 'Founder post from signals',
    description: 'Turn current signals/intel into a founder-voice post.',
    example_prompts: ['Write a post from these signals'],
    required_context: ['signals'],
    optional_context: ['voice'],
    agents: ['pilot', 'scribe'],
    tools: ['gemini'],
    output_kind: 'draft',
    safety_level: 'draft_only',
    enabled: true,
  },
  {
    id: 'blog_outline',
    name: 'Blog outline',
    description: 'Outline a blog post around a topic and audience.',
    example_prompts: ['Outline a blog on AI SDRs'],
    required_context: ['topic'],
    optional_context: ['audience', 'goal'],
    agents: ['pilot', 'scribe'],
    tools: ['gemini'],
    output_kind: 'draft',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'report_summary',
    name: 'Report summary',
    description: 'Summarize a long report, doc, or transcript.',
    example_prompts: ['Summarize this report'],
    required_context: ['source'],
    optional_context: ['length'],
    agents: ['pilot', 'scribe'],
    tools: ['gemini'],
    output_kind: 'chat',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'campaign_copy',
    name: 'Campaign copy',
    description: 'Draft campaign copy (email, ad, page) DRAFT-ONLY.',
    example_prompts: ['Draft a campaign for our new feature'],
    required_context: ['campaign_goal'],
    optional_context: ['audience', 'offer'],
    agents: ['pilot', 'scribe', 'penn'],
    tools: ['gemini'],
    output_kind: 'draft',
    safety_level: 'draft_only',
    enabled: true,
  },

  // ──────────────── Ops / intelligence ────────────────
  {
    id: 'daily_brief',
    name: 'Daily brief',
    description: 'Brief on what happened across pipeline, signals, drafts.',
    example_prompts: ['Brief me on today'],
    required_context: [],
    optional_context: [],
    agents: ['pilot', 'hawk'],
    tools: ['supabase'],
    output_kind: 'chat',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'company_brain_update',
    name: 'Update Company Brain',
    description: 'Update Company Brain profile (ICP, offer, competitors).',
    example_prompts: ['Update our ICP'],
    required_context: ['field'],
    optional_context: [],
    agents: ['pilot'],
    tools: ['supabase'],
    output_kind: 'chat',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'onboarding_update',
    name: 'Onboarding update',
    description: 'Continue onboarding to give Pilot more context.',
    example_prompts: ['Help me finish setup'],
    required_context: [],
    optional_context: [],
    agents: ['pilot'],
    tools: ['supabase'],
    output_kind: 'chat',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'account_research',
    name: 'Account research',
    description: 'Deep-dive research on a specific target account.',
    example_prompts: ['Research acme.com'],
    required_context: ['account'],
    optional_context: [],
    agents: ['pilot', 'hawk'],
    tools: ['firecrawl', 'gemini'],
    output_kind: 'report',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'qa_report',
    name: 'QA report',
    description: 'Quality-check a previous workflow output.',
    example_prompts: ['Why did this run only return 2?'],
    required_context: ['artifact'],
    optional_context: [],
    agents: ['pilot', 'aria'],
    tools: ['gemini'],
    output_kind: 'chat',
    safety_level: 'safe',
    enabled: true,
  },
  {
    id: 'workflow_status_check',
    name: 'Workflow status',
    description: 'Check status of running/completed workflows.',
    example_prompts: ['What is running right now?'],
    required_context: [],
    optional_context: [],
    agents: ['pilot'],
    tools: ['supabase'],
    output_kind: 'chat',
    safety_level: 'safe',
    enabled: true,
  },

  // ──────────────── General Q&A ────────────────
  {
    id: 'general_qa',
    name: 'General Q&A',
    description: 'Pilot answers conversationally from registry + context.',
    example_prompts: ['What can you do?', 'How does this work?', 'What does Scout do?'],
    required_context: [],
    optional_context: [],
    agents: ['pilot'],
    tools: ['gemini'],
    output_kind: 'chat',
    safety_level: 'safe',
    enabled: true,
  },
];

export function getCapability(id: string): WorkflowCapability | undefined {
  return WORKFLOW_CAPABILITIES.find((c) => c.id === id);
}

export function capabilitiesForAgent(agent: AgentId): WorkflowCapability[] {
  return WORKFLOW_CAPABILITIES.filter((c) => c.agents.includes(agent) && c.enabled);
}

export function summarizeCapabilitiesForPrompt(): string {
  return WORKFLOW_CAPABILITIES
    .filter((c) => c.enabled)
    .map((c) => `- ${c.id} (${c.agents.join('/')}): ${c.description} [safety=${c.safety_level}]`)
    .join('\n');
}
