// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Env-overridable so local QA can target a TEST project without editing this
// generated file. Defaults to the production values when the env vars are unset,
// so the production bundle behaves exactly as before. Set VITE_SUPABASE_URL and
// VITE_SUPABASE_PUBLISHABLE_KEY in a gitignored .env.local to point elsewhere.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ?? "https://wqnigjhcwjxtmordrwno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indxbmlnamhjd2p4dG1vcmRyd25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxNzQ0NjUsImV4cCI6MjA5Mjc1MDQ2NX0.GelbMIlFnirbVFu50ywoFekbHSBcg_v2hc3dIVHMPog";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Supabase client misconfigured: missing URL or publishable key in the production bundle.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
